common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: flockr

development:
  <<: *common
  database: flockr_development

test:
  <<: *common
  database: flockr_test

production:
  <<: *common
  database: flockr_production
